server:
  port: 8080
  servlet:
    context-path: /redis_cache
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: agytorudhcv11
    url: jdbc:mysql://localhost:3306/redis_cache?useSSL=false
  jpa:
    show-sql: true


  redis:
    host: localhost
    port: 6379
    database: 2

